[package]
name = "taskmgr-linux"
version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
taskmgr-core = { path = "../taskmgr-core" }

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true
png.workspace = true
wayland-client.workspace = true
wayland-protocols.workspace = true
wayland-protocols-plasma.workspace = true
wayland-protocols-wlr.workspace = true
x11rb.workspace = true

[dev-dependencies]
tempfile = "3.23.0"
