// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'third_party/taskmgr_core.dart';
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `platform_provider`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `from`, `from`

Future<BackendHandle> startBackend({required BackendOptions options}) =>
    RustLib.instance.api.crateApiStartBackend(options: options);

Stream<BridgeBackendEvent> watchBackend({required BackendHandle handle}) =>
    RustLib.instance.api.crateApiWatchBackend(handle: handle);

Future<void> updateOptions({
  required BackendHandle handle,
  required BackendOptions options,
}) => RustLib.instance.api.crateApiUpdateOptions(
  handle: handle,
  options: options,
);

Future<void> requestRefresh({required BackendHandle handle, PageId? page}) =>
    RustLib.instance.api.crateApiRequestRefresh(handle: handle, page: page);

Future<PrivilegeResult> openPrivilegedSession({
  required BackendHandle handle,
}) => RustLib.instance.api.crateApiOpenPrivilegedSession(handle: handle);

Future<ActionResult> executeAction({
  required BackendHandle handle,
  required BridgeActionRequest request,
}) => RustLib.instance.api.crateApiExecuteAction(
  handle: handle,
  request: request,
);

Future<SettingsLoadResult> loadSettings() =>
    RustLib.instance.api.crateApiLoadSettings();

Future<void> saveSettings({required UiSettings settings}) =>
    RustLib.instance.api.crateApiSaveSettings(settings: settings);

Future<void> shutdownBackend({required BackendHandle handle}) =>
    RustLib.instance.api.crateApiShutdownBackend(handle: handle);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BackendHandle>>
abstract class BackendHandle implements RustOpaqueInterface {}

@freezed
sealed class BridgeActionRequest with _$BridgeActionRequest {
  const BridgeActionRequest._();

  const factory BridgeActionRequest.runTask({required String commandLine}) =
      BridgeActionRequest_RunTask;
  const factory BridgeActionRequest.endProcess({
    required ProcessIdentity identity,
    required bool includeDescendants,
  }) = BridgeActionRequest_EndProcess;
  const factory BridgeActionRequest.setPriority({
    required ProcessIdentity identity,
    required ProcessPriority priority,
  }) = BridgeActionRequest_SetPriority;
  const factory BridgeActionRequest.setNice({
    required ProcessIdentity identity,
    required int nice,
  }) = BridgeActionRequest_SetNice;
  const factory BridgeActionRequest.setAffinity({
    required ProcessIdentity identity,
    required Uint32List logicalProcessors,
  }) = BridgeActionRequest_SetAffinity;
  const factory BridgeActionRequest.openFileLocation({
    required ProcessIdentity identity,
  }) = BridgeActionRequest_OpenFileLocation;
  const factory BridgeActionRequest.window({
    required ApplicationIdentity identity,
    required WindowAction operation,
  }) = BridgeActionRequest_Window;
  const factory BridgeActionRequest.arrangeWindows({
    required List<ApplicationIdentity> identities,
    required WindowArrangement arrangement,
  }) = BridgeActionRequest_ArrangeWindows;
  const factory BridgeActionRequest.userSession({
    required UserSessionIdentity identity,
    required UserAction operation,
    String? title,
    String? message,
  }) = BridgeActionRequest_UserSession;
}

@freezed
sealed class BridgeBackendEvent with _$BridgeBackendEvent {
  const BridgeBackendEvent._();

  const factory BridgeBackendEvent.capabilities(PlatformCapabilities field0) =
      BridgeBackendEvent_Capabilities;
  const factory BridgeBackendEvent.applications({
    required SnapshotMeta meta,
    required ApplicationsData data,
  }) = BridgeBackendEvent_Applications;
  const factory BridgeBackendEvent.processes({
    required SnapshotMeta meta,
    required ProcessesData data,
  }) = BridgeBackendEvent_Processes;
  const factory BridgeBackendEvent.performance({
    required SnapshotMeta meta,
    required PerformanceData data,
  }) = BridgeBackendEvent_Performance;
  const factory BridgeBackendEvent.cpu({
    required SnapshotMeta meta,
    required CpuData data,
  }) = BridgeBackendEvent_Cpu;
  const factory BridgeBackendEvent.gpu({
    required SnapshotMeta meta,
    required GpuData data,
  }) = BridgeBackendEvent_Gpu;
  const factory BridgeBackendEvent.network({
    required SnapshotMeta meta,
    required NetworkData data,
  }) = BridgeBackendEvent_Network;
  const factory BridgeBackendEvent.users({
    required SnapshotMeta meta,
    required UsersData data,
  }) = BridgeBackendEvent_Users;
  const factory BridgeBackendEvent.pageUnavailable({
    required PageId page,
    required SnapshotMeta meta,
  }) = BridgeBackendEvent_PageUnavailable;
  const factory BridgeBackendEvent.privilegeChanged(PrivilegeResult field0) =
      BridgeBackendEvent_PrivilegeChanged;
}
