// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'third_party/taskmgr_core.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BackendEventPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendEvent;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BackendHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SnapshotDataPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSnapshotData;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  BackendEvent
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendEvent(
    dynamic raw,
  );

  @protected
  BackendHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendHandle(
    dynamic raw,
  );

  @protected
  SnapshotData
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSnapshotData(
    dynamic raw,
  );

  @protected
  BackendEvent
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendEvent(
    dynamic raw,
  );

  @protected
  BackendHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendHandle(
    dynamic raw,
  );

  @protected
  SnapshotData
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSnapshotData(
    dynamic raw,
  );

  @protected
  BackendEvent
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendEvent(
    dynamic raw,
  );

  @protected
  BackendHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendHandle(
    dynamic raw,
  );

  @protected
  SnapshotData
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSnapshotData(
    dynamic raw,
  );

  @protected
  RustStreamSink<BridgeBackendEvent>
  dco_decode_StreamSink_bridge_backend_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ActionKind dco_decode_action_kind(dynamic raw);

  @protected
  ActionResult dco_decode_action_result(dynamic raw);

  @protected
  ActionStatus dco_decode_action_status(dynamic raw);

  @protected
  ApplicationIdentity dco_decode_application_identity(dynamic raw);

  @protected
  ApplicationRow dco_decode_application_row(dynamic raw);

  @protected
  ApplicationStatus dco_decode_application_status(dynamic raw);

  @protected
  ApplicationViewMode dco_decode_application_view_mode(dynamic raw);

  @protected
  ApplicationsData dco_decode_applications_data(dynamic raw);

  @protected
  Architecture dco_decode_architecture(dynamic raw);

  @protected
  Availability dco_decode_availability(dynamic raw);

  @protected
  BackendError dco_decode_backend_error(dynamic raw);

  @protected
  BackendOptions dco_decode_backend_options(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ApplicationIdentity dco_decode_box_autoadd_application_identity(dynamic raw);

  @protected
  ApplicationsData dco_decode_box_autoadd_applications_data(dynamic raw);

  @protected
  BackendError dco_decode_box_autoadd_backend_error(dynamic raw);

  @protected
  BackendOptions dco_decode_box_autoadd_backend_options(dynamic raw);

  @protected
  BridgeActionRequest dco_decode_box_autoadd_bridge_action_request(dynamic raw);

  @protected
  CpuData dco_decode_box_autoadd_cpu_data(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  GpuData dco_decode_box_autoadd_gpu_data(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  NetworkData dco_decode_box_autoadd_network_data(dynamic raw);

  @protected
  PageId dco_decode_box_autoadd_page_id(dynamic raw);

  @protected
  PerformanceData dco_decode_box_autoadd_performance_data(dynamic raw);

  @protected
  PlatformCapabilities dco_decode_box_autoadd_platform_capabilities(
    dynamic raw,
  );

  @protected
  PrivilegeResult dco_decode_box_autoadd_privilege_result(dynamic raw);

  @protected
  ProcessIdentity dco_decode_box_autoadd_process_identity(dynamic raw);

  @protected
  ProcessesData dco_decode_box_autoadd_processes_data(dynamic raw);

  @protected
  SnapshotMeta dco_decode_box_autoadd_snapshot_meta(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  UiSettings dco_decode_box_autoadd_ui_settings(dynamic raw);

  @protected
  UserSessionIdentity dco_decode_box_autoadd_user_session_identity(dynamic raw);

  @protected
  UsersData dco_decode_box_autoadd_users_data(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  BridgeActionRequest dco_decode_bridge_action_request(dynamic raw);

  @protected
  BridgeBackendEvent dco_decode_bridge_backend_event(dynamic raw);

  @protected
  ColumnId dco_decode_column_id(dynamic raw);

  @protected
  ColumnLayout dco_decode_column_layout(dynamic raw);

  @protected
  CpuData dco_decode_cpu_data(dynamic raw);

  @protected
  CpuMetricGroup dco_decode_cpu_metric_group(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GpuAdapter dco_decode_gpu_adapter(dynamic raw);

  @protected
  GpuData dco_decode_gpu_data(dynamic raw);

  @protected
  GpuEngine dco_decode_gpu_engine(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<ActionKind> dco_decode_list_action_kind(dynamic raw);

  @protected
  List<ApplicationIdentity> dco_decode_list_application_identity(dynamic raw);

  @protected
  List<ApplicationRow> dco_decode_list_application_row(dynamic raw);

  @protected
  List<ColumnId> dco_decode_list_column_id(dynamic raw);

  @protected
  List<ColumnLayout> dco_decode_list_column_layout(dynamic raw);

  @protected
  List<CpuMetricGroup> dco_decode_list_cpu_metric_group(dynamic raw);

  @protected
  List<GpuAdapter> dco_decode_list_gpu_adapter(dynamic raw);

  @protected
  List<GpuEngine> dco_decode_list_gpu_engine(dynamic raw);

  @protected
  List<Float64List> dco_decode_list_list_prim_f_64_strict(dynamic raw);

  @protected
  List<MetricValue> dco_decode_list_metric_value(dynamic raw);

  @protected
  List<NetworkInterface> dco_decode_list_network_interface(dynamic raw);

  @protected
  List<PageCapability> dco_decode_list_page_capability(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProcessRow> dco_decode_list_process_row(dynamic raw);

  @protected
  List<UserSession> dco_decode_list_user_session(dynamic raw);

  @protected
  MetricValue dco_decode_metric_value(dynamic raw);

  @protected
  NetworkData dco_decode_network_data(dynamic raw);

  @protected
  NetworkInterface dco_decode_network_interface(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BackendError? dco_decode_opt_box_autoadd_backend_error(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  PageId? dco_decode_opt_box_autoadd_page_id(dynamic raw);

  @protected
  ProcessIdentity? dco_decode_opt_box_autoadd_process_identity(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  Uint32List? dco_decode_opt_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PageCapability dco_decode_page_capability(dynamic raw);

  @protected
  PageId dco_decode_page_id(dynamic raw);

  @protected
  PerformanceData dco_decode_performance_data(dynamic raw);

  @protected
  PlatformCapabilities dco_decode_platform_capabilities(dynamic raw);

  @protected
  PlatformKind dco_decode_platform_kind(dynamic raw);

  @protected
  PrivilegeResult dco_decode_privilege_result(dynamic raw);

  @protected
  PrivilegeState dco_decode_privilege_state(dynamic raw);

  @protected
  ProcessIdentity dco_decode_process_identity(dynamic raw);

  @protected
  ProcessPriority dco_decode_process_priority(dynamic raw);

  @protected
  ProcessRow dco_decode_process_row(dynamic raw);

  @protected
  ProcessesData dco_decode_processes_data(dynamic raw);

  @protected
  SettingsLoadResult dco_decode_settings_load_result(dynamic raw);

  @protected
  SnapshotMeta dco_decode_snapshot_meta(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UiSettings dco_decode_ui_settings(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdateSpeed dco_decode_update_speed(dynamic raw);

  @protected
  UserAction dco_decode_user_action(dynamic raw);

  @protected
  UserSession dco_decode_user_session(dynamic raw);

  @protected
  UserSessionIdentity dco_decode_user_session_identity(dynamic raw);

  @protected
  UsersData dco_decode_users_data(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WindowAction dco_decode_window_action(dynamic raw);

  @protected
  WindowArrangement dco_decode_window_arrangement(dynamic raw);

  @protected
  WindowGeometry dco_decode_window_geometry(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  BackendEvent
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendEvent(
    SseDeserializer deserializer,
  );

  @protected
  BackendHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendHandle(
    SseDeserializer deserializer,
  );

  @protected
  SnapshotData
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSnapshotData(
    SseDeserializer deserializer,
  );

  @protected
  BackendEvent
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendEvent(
    SseDeserializer deserializer,
  );

  @protected
  BackendHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendHandle(
    SseDeserializer deserializer,
  );

  @protected
  SnapshotData
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSnapshotData(
    SseDeserializer deserializer,
  );

  @protected
  BackendEvent
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendEvent(
    SseDeserializer deserializer,
  );

  @protected
  BackendHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendHandle(
    SseDeserializer deserializer,
  );

  @protected
  SnapshotData
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSnapshotData(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<BridgeBackendEvent>
  sse_decode_StreamSink_bridge_backend_event_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActionKind sse_decode_action_kind(SseDeserializer deserializer);

  @protected
  ActionResult sse_decode_action_result(SseDeserializer deserializer);

  @protected
  ActionStatus sse_decode_action_status(SseDeserializer deserializer);

  @protected
  ApplicationIdentity sse_decode_application_identity(
    SseDeserializer deserializer,
  );

  @protected
  ApplicationRow sse_decode_application_row(SseDeserializer deserializer);

  @protected
  ApplicationStatus sse_decode_application_status(SseDeserializer deserializer);

  @protected
  ApplicationViewMode sse_decode_application_view_mode(
    SseDeserializer deserializer,
  );

  @protected
  ApplicationsData sse_decode_applications_data(SseDeserializer deserializer);

  @protected
  Architecture sse_decode_architecture(SseDeserializer deserializer);

  @protected
  Availability sse_decode_availability(SseDeserializer deserializer);

  @protected
  BackendError sse_decode_backend_error(SseDeserializer deserializer);

  @protected
  BackendOptions sse_decode_backend_options(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ApplicationIdentity sse_decode_box_autoadd_application_identity(
    SseDeserializer deserializer,
  );

  @protected
  ApplicationsData sse_decode_box_autoadd_applications_data(
    SseDeserializer deserializer,
  );

  @protected
  BackendError sse_decode_box_autoadd_backend_error(
    SseDeserializer deserializer,
  );

  @protected
  BackendOptions sse_decode_box_autoadd_backend_options(
    SseDeserializer deserializer,
  );

  @protected
  BridgeActionRequest sse_decode_box_autoadd_bridge_action_request(
    SseDeserializer deserializer,
  );

  @protected
  CpuData sse_decode_box_autoadd_cpu_data(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  GpuData sse_decode_box_autoadd_gpu_data(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  NetworkData sse_decode_box_autoadd_network_data(SseDeserializer deserializer);

  @protected
  PageId sse_decode_box_autoadd_page_id(SseDeserializer deserializer);

  @protected
  PerformanceData sse_decode_box_autoadd_performance_data(
    SseDeserializer deserializer,
  );

  @protected
  PlatformCapabilities sse_decode_box_autoadd_platform_capabilities(
    SseDeserializer deserializer,
  );

  @protected
  PrivilegeResult sse_decode_box_autoadd_privilege_result(
    SseDeserializer deserializer,
  );

  @protected
  ProcessIdentity sse_decode_box_autoadd_process_identity(
    SseDeserializer deserializer,
  );

  @protected
  ProcessesData sse_decode_box_autoadd_processes_data(
    SseDeserializer deserializer,
  );

  @protected
  SnapshotMeta sse_decode_box_autoadd_snapshot_meta(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  UiSettings sse_decode_box_autoadd_ui_settings(SseDeserializer deserializer);

  @protected
  UserSessionIdentity sse_decode_box_autoadd_user_session_identity(
    SseDeserializer deserializer,
  );

  @protected
  UsersData sse_decode_box_autoadd_users_data(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  BridgeActionRequest sse_decode_bridge_action_request(
    SseDeserializer deserializer,
  );

  @protected
  BridgeBackendEvent sse_decode_bridge_backend_event(
    SseDeserializer deserializer,
  );

  @protected
  ColumnId sse_decode_column_id(SseDeserializer deserializer);

  @protected
  ColumnLayout sse_decode_column_layout(SseDeserializer deserializer);

  @protected
  CpuData sse_decode_cpu_data(SseDeserializer deserializer);

  @protected
  CpuMetricGroup sse_decode_cpu_metric_group(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GpuAdapter sse_decode_gpu_adapter(SseDeserializer deserializer);

  @protected
  GpuData sse_decode_gpu_data(SseDeserializer deserializer);

  @protected
  GpuEngine sse_decode_gpu_engine(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<ActionKind> sse_decode_list_action_kind(SseDeserializer deserializer);

  @protected
  List<ApplicationIdentity> sse_decode_list_application_identity(
    SseDeserializer deserializer,
  );

  @protected
  List<ApplicationRow> sse_decode_list_application_row(
    SseDeserializer deserializer,
  );

  @protected
  List<ColumnId> sse_decode_list_column_id(SseDeserializer deserializer);

  @protected
  List<ColumnLayout> sse_decode_list_column_layout(
    SseDeserializer deserializer,
  );

  @protected
  List<CpuMetricGroup> sse_decode_list_cpu_metric_group(
    SseDeserializer deserializer,
  );

  @protected
  List<GpuAdapter> sse_decode_list_gpu_adapter(SseDeserializer deserializer);

  @protected
  List<GpuEngine> sse_decode_list_gpu_engine(SseDeserializer deserializer);

  @protected
  List<Float64List> sse_decode_list_list_prim_f_64_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<MetricValue> sse_decode_list_metric_value(SseDeserializer deserializer);

  @protected
  List<NetworkInterface> sse_decode_list_network_interface(
    SseDeserializer deserializer,
  );

  @protected
  List<PageCapability> sse_decode_list_page_capability(
    SseDeserializer deserializer,
  );

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProcessRow> sse_decode_list_process_row(SseDeserializer deserializer);

  @protected
  List<UserSession> sse_decode_list_user_session(SseDeserializer deserializer);

  @protected
  MetricValue sse_decode_metric_value(SseDeserializer deserializer);

  @protected
  NetworkData sse_decode_network_data(SseDeserializer deserializer);

  @protected
  NetworkInterface sse_decode_network_interface(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BackendError? sse_decode_opt_box_autoadd_backend_error(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  PageId? sse_decode_opt_box_autoadd_page_id(SseDeserializer deserializer);

  @protected
  ProcessIdentity? sse_decode_opt_box_autoadd_process_identity(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  Uint32List? sse_decode_opt_list_prim_u_32_strict(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PageCapability sse_decode_page_capability(SseDeserializer deserializer);

  @protected
  PageId sse_decode_page_id(SseDeserializer deserializer);

  @protected
  PerformanceData sse_decode_performance_data(SseDeserializer deserializer);

  @protected
  PlatformCapabilities sse_decode_platform_capabilities(
    SseDeserializer deserializer,
  );

  @protected
  PlatformKind sse_decode_platform_kind(SseDeserializer deserializer);

  @protected
  PrivilegeResult sse_decode_privilege_result(SseDeserializer deserializer);

  @protected
  PrivilegeState sse_decode_privilege_state(SseDeserializer deserializer);

  @protected
  ProcessIdentity sse_decode_process_identity(SseDeserializer deserializer);

  @protected
  ProcessPriority sse_decode_process_priority(SseDeserializer deserializer);

  @protected
  ProcessRow sse_decode_process_row(SseDeserializer deserializer);

  @protected
  ProcessesData sse_decode_processes_data(SseDeserializer deserializer);

  @protected
  SettingsLoadResult sse_decode_settings_load_result(
    SseDeserializer deserializer,
  );

  @protected
  SnapshotMeta sse_decode_snapshot_meta(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UiSettings sse_decode_ui_settings(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdateSpeed sse_decode_update_speed(SseDeserializer deserializer);

  @protected
  UserAction sse_decode_user_action(SseDeserializer deserializer);

  @protected
  UserSession sse_decode_user_session(SseDeserializer deserializer);

  @protected
  UserSessionIdentity sse_decode_user_session_identity(
    SseDeserializer deserializer,
  );

  @protected
  UsersData sse_decode_users_data(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WindowAction sse_decode_window_action(SseDeserializer deserializer);

  @protected
  WindowArrangement sse_decode_window_arrangement(SseDeserializer deserializer);

  @protected
  WindowGeometry sse_decode_window_geometry(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendEvent(
    BackendEvent self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendHandle(
    BackendHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSnapshotData(
    SnapshotData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendEvent(
    BackendEvent self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendHandle(
    BackendHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSnapshotData(
    SnapshotData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendEvent(
    BackendEvent self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendHandle(
    BackendHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSnapshotData(
    SnapshotData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bridge_backend_event_Sse(
    RustStreamSink<BridgeBackendEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_action_kind(ActionKind self, SseSerializer serializer);

  @protected
  void sse_encode_action_result(ActionResult self, SseSerializer serializer);

  @protected
  void sse_encode_action_status(ActionStatus self, SseSerializer serializer);

  @protected
  void sse_encode_application_identity(
    ApplicationIdentity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_application_row(
    ApplicationRow self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_application_status(
    ApplicationStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_application_view_mode(
    ApplicationViewMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_applications_data(
    ApplicationsData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_architecture(Architecture self, SseSerializer serializer);

  @protected
  void sse_encode_availability(Availability self, SseSerializer serializer);

  @protected
  void sse_encode_backend_error(BackendError self, SseSerializer serializer);

  @protected
  void sse_encode_backend_options(
    BackendOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_application_identity(
    ApplicationIdentity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_applications_data(
    ApplicationsData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_backend_error(
    BackendError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_backend_options(
    BackendOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_action_request(
    BridgeActionRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_cpu_data(CpuData self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_gpu_data(GpuData self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_network_data(
    NetworkData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_page_id(PageId self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_performance_data(
    PerformanceData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_platform_capabilities(
    PlatformCapabilities self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_privilege_result(
    PrivilegeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_process_identity(
    ProcessIdentity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_processes_data(
    ProcessesData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_snapshot_meta(
    SnapshotMeta self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ui_settings(
    UiSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_user_session_identity(
    UserSessionIdentity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_users_data(
    UsersData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_action_request(
    BridgeActionRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_backend_event(
    BridgeBackendEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_column_id(ColumnId self, SseSerializer serializer);

  @protected
  void sse_encode_column_layout(ColumnLayout self, SseSerializer serializer);

  @protected
  void sse_encode_cpu_data(CpuData self, SseSerializer serializer);

  @protected
  void sse_encode_cpu_metric_group(
    CpuMetricGroup self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_gpu_adapter(GpuAdapter self, SseSerializer serializer);

  @protected
  void sse_encode_gpu_data(GpuData self, SseSerializer serializer);

  @protected
  void sse_encode_gpu_engine(GpuEngine self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_action_kind(
    List<ActionKind> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_application_identity(
    List<ApplicationIdentity> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_application_row(
    List<ApplicationRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_column_id(List<ColumnId> self, SseSerializer serializer);

  @protected
  void sse_encode_list_column_layout(
    List<ColumnLayout> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_cpu_metric_group(
    List<CpuMetricGroup> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_gpu_adapter(
    List<GpuAdapter> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_gpu_engine(
    List<GpuEngine> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_prim_f_64_strict(
    List<Float64List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_metric_value(
    List<MetricValue> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_network_interface(
    List<NetworkInterface> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_page_capability(
    List<PageCapability> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_process_row(
    List<ProcessRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_user_session(
    List<UserSession> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_metric_value(MetricValue self, SseSerializer serializer);

  @protected
  void sse_encode_network_data(NetworkData self, SseSerializer serializer);

  @protected
  void sse_encode_network_interface(
    NetworkInterface self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_backend_error(
    BackendError? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_page_id(
    PageId? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_process_identity(
    ProcessIdentity? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_32_strict(
    Uint32List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_page_capability(
    PageCapability self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_page_id(PageId self, SseSerializer serializer);

  @protected
  void sse_encode_performance_data(
    PerformanceData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_platform_capabilities(
    PlatformCapabilities self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_platform_kind(PlatformKind self, SseSerializer serializer);

  @protected
  void sse_encode_privilege_result(
    PrivilegeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_privilege_state(
    PrivilegeState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_process_identity(
    ProcessIdentity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_process_priority(
    ProcessPriority self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_process_row(ProcessRow self, SseSerializer serializer);

  @protected
  void sse_encode_processes_data(ProcessesData self, SseSerializer serializer);

  @protected
  void sse_encode_settings_load_result(
    SettingsLoadResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_snapshot_meta(SnapshotMeta self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_ui_settings(UiSettings self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_speed(UpdateSpeed self, SseSerializer serializer);

  @protected
  void sse_encode_user_action(UserAction self, SseSerializer serializer);

  @protected
  void sse_encode_user_session(UserSession self, SseSerializer serializer);

  @protected
  void sse_encode_user_session_identity(
    UserSessionIdentity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_users_data(UsersData self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_window_action(WindowAction self, SseSerializer serializer);

  @protected
  void sse_encode_window_arrangement(
    WindowArrangement self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_window_geometry(
    WindowGeometry self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendEvent(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendEvent(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendEvent(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendEvent(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendHandle(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSnapshotData(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSnapshotData(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSnapshotData(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSnapshotData(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendEvent(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendEvent(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBackendHandle(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSnapshotData(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSnapshotData(
    int ptr,
  );
}
